name: PGN grammar CI

on:
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test_unixlike:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: tree-sitter/setup-action@1868a545ffb91bdc221d14a168b5b6d8de4a28b3 # v2
        with:
          tree-sitter-ref: v0.25.8
      - name: Run test commands
        shell: bash
        run: |
          tree-sitter generate
          tree-sitter test
          ./script/parse_examples.sh
